name: Build, Test, Deploy

on:
  push:
    branches: [ "main" ]  # Trigger workflow on push to main branch
  pull_request:
    branches: [ "main" ]  # Trigger workflow on PR to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Run Tests
    #   run: |
    #     python -m pytest tests/

    - name: Build Docker Image
      run: |
        docker compose up -d
        docker ps

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Run Uvicorn/FastAPI
    #   run: |
    #     uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
